# Generated by Django 2.1.1 on 2019-02-25 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptOfficer',
            fields=[
                ('dept_loginid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('dept_password', models.CharField(max_length=40)),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_email', models.CharField(max_length=40)),
                ('dept_contact', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder', models.CharField(max_length=40)),
                ('rating', models.CharField(max_length=40)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('dept', models.CharField(max_length=40)),
                ('dept_loginid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dept.DeptOfficer')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.CharField(default='0', max_length=40)),
                ('score2', models.CharField(default='0', max_length=40)),
                ('dept_loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.DeptOfficer')),
            ],
        ),
    ]
