from django.urls import path
from . import views

urlpatterns=[
    path('',views.dipp_home,name='dipp_home'),
    path('add_dept/',views.add_dept,name='add_dept'),
    path('add_dept_action/',views.add_dept_action,name='add_dept_action'),
    path('add_sh/',views.add_sh,name='add_sh'),
    path('add_sh_action/',views.add_sh_action,name='add_sh_action'),
    path('add_monitory_meeting/',views.add_monitory_meeting,name='add_monitory_meeting'),
    path('add_monitory_meeting_action/',views.add_monitory_meeting_action,name='add_monitory_meeting_action'),
    path('view_upcoming_meetings_action/',views.view_upcoming_meetings_action,name='view_upcoming_meetings_action'),
    path('view_prev_meeting/',views.view_prev_meeting,name='view_prev_meeting'),
    path('upload_minute/<str:mid>',views.upload_minute,name='upload_minute'),
    path('add_meeting/',views.add_meeting,name='add_meeting'),
    path('add_meeting_action/',views.add_meeting_action,name='add_meeting_action'),
    path('view_upcoming_normalmeetings/',views.view_upcoming_normalmeetings,name='view_upcoming_normalmeetings'),
    path('view_prev_normalmeeting/',views.view_prev_normalmeeting,name='view_prev_normalmeeting'),
    path('upload_minute/<str:mid>',views.upload_minute,name='upload_minute'),
    path('upload_normalmeeting_minute/<str:mid>',views.upload_normalmeeting_minute,name='upload_normalmeeting_minute'),
    path('add_status_report/',views.add_status_report,name='add_status_report'),
    path('add_status_report_action/',views.add_status_report_action,name='add_status_report_action'),
    path('view_status_report/',views.view_status_report,name='view_status_report'),
    path('notify/',views.notify,name='notify'),
    path('notify_action/',views.notify_action,name='notify_action'),
    path('view_notification/',views.view_notification,name='view_notification'),
    path('add_target/',views.add_target,name='add_target'),
    path('add_target_action/',views.add_target_action,name='add_target_action'),
    path('ajax/load_action/', views.load_action, name='ajax_load_action'),
    # path('add_action_point/',views.add_action_point,name='add_action_point'),
    path('view_past_target/',views.view_past_target,name='view_past_target'),
    path('view_current_target/',views.view_current_target,name='view_current_target'),
    path('update_action_points/',views.update_action_points,name='update_action_points'),
    path('logout/',views.logout,name='logout'),
    path('view_target_analysis/',views.view_target_analysis,name='view_target_analysis'),
    path('view_achievement_analysis/',views.view_achievement_analysis,name='view_achievement_analysis'),
    path('view_feedback_analysis/',views.view_feedback_analysis,name='view_feedback_analysis'),
    path('view_ap_analysis/',views.view_ap_analysis,name='view_ap_analysis'),
    path('view_comparision_analysis/',views.view_comparision_analysis,name='view_comparision_analysis'),
    path('show_ranking/',views.show_ranking,name='show_ranking'),

    path('sort_by_pm/',views.sort_by_pm,name='sort_by_pm'),
    path('sort_by_date_pnm/',views.sort_by_date_pnm,name='sort_by_date_pnm'),
    path('sort_by_date_um/',views.sort_by_date_um,name='sort_by_date_um'),
    path('sort_by_date_unm/',views.sort_by_date_unm,name='sort_by_date_unm'),
    path('sort_by_date_vct/',views.sort_by_date_vct,name='sort_by_date_vct'),
    path('sort_by_date_vpt/',views.sort_by_date_vpt,name='sort_by_date_vpt'),
    path('sort_by_date_vsr_dipp/',views.sort_by_date_vsr_dipp,name='sort_by_date_vsr_dipp'),
    path('download_ap_dipp/',views.download_ap_dipp,name='download_ap_dipp'),
    path('dept_summary/',views.dept_summary,name='dept_summary'),

]
