# Generated by Django 2.1.1 on 2019-02-25 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPoints',
            fields=[
                ('action_no', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('action_name', models.CharField(default='NULL', max_length=100)),
                ('action_objective', models.CharField(default='NULL', max_length=200)),
                ('action_description', models.CharField(default='NULL', max_length=500)),
                ('update_time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DippOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dipp_loginid', models.CharField(max_length=40)),
                ('dipp_password', models.CharField(max_length=40)),
                ('dipp_email', models.CharField(max_length=40)),
                ('dipp_contact', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('subject', models.CharField(max_length=40)),
                ('meeting_time', models.TimeField()),
                ('upload_minute', models.FileField(blank=True, default='not uploaded', null=True, upload_to='')),
                ('description', models.TextField(default='', max_length=400)),
                ('with_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.DeptOfficer')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring_Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('subject', models.CharField(max_length=40)),
                ('meeting_time', models.TimeField()),
                ('upload_minute', models.FileField(blank=True, default='not uploaded', null=True, upload_to='')),
                ('description', models.TextField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=400)),
                ('department', models.CharField(max_length=40)),
                ('actionpoint_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipp.ActionPoints')),
            ],
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_upload', models.DateField(default=django.utils.timezone.now)),
                ('month', models.CharField(max_length=40)),
                ('upload_statusreport', models.FileField(blank=True, default='not uploaded', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_assignment', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='0', max_length=10)),
                ('desc_of_target', models.CharField(max_length=400)),
                ('report', models.CharField(default='not updated yet', max_length=400)),
                ('actionpoint_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipp.ActionPoints')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.DeptOfficer')),
            ],
        ),
    ]
