# Generated by Django 2.0.2 on 2019-03-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
        ('dipp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept_action_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionpoint_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipp.ActionPoints')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.DeptOfficer')),
            ],
        ),
    ]
