# Generated by Django 2.1.7 on 2019-03-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
        ('dipp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(default='not updated yet', max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='actionpoints',
            name='typee',
            field=models.CharField(default='Non-Numeric', max_length=100),
        ),
        migrations.AddField(
            model_name='box',
            name='a_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipp.ActionPoints'),
        ),
        migrations.AddField(
            model_name='box',
            name='d_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.DeptOfficer'),
        ),
    ]
