# Generated by Django 2.1.1 on 2019-02-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring_Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('subject', models.CharField(max_length=40)),
                ('meeting_time', models.TimeField()),
                ('upload_minute', models.FileField(blank=True, default='not uploaded', null=True, upload_to='')),
            ],
        ),
    ]
