# Generated by Django 2.1.1 on 2019-03-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoints',
            name='box',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='actionpoints',
            name='typee',
            field=models.CharField(default='Non-Numeric', max_length=20),
        ),
    ]
