# Generated by Django 2.1.7 on 2019-03-02 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dipp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDipp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.CharField(default='Update', max_length=40)),
                ('type', models.CharField(max_length=400)),
            ],
        ),
    ]
