# Generated by Django 2.1.1 on 2019-02-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipp', '0002_monitoring_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring_meeting',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
