# Generated by Django 2.1.1 on 2019-02-19 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dipp', '0004_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_upload', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('month', models.DateField()),
                ('upload_statusreport', models.FileField(blank=True, default='not uploaded', null=True, upload_to='')),
            ],
        ),
    ]
