# Generated by Django 2.1.1 on 2019-02-19 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dipp', '0006_auto_20190220_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='date_of_upload',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
