# Generated by Django 2.1.1 on 2019-02-20 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dipp', '0007_auto_20190220_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=400)),
                ('department', models.CharField(max_length=40)),
            ],
        ),
    ]
